"""initial

Revision ID: 22b96fe61bcc
Revises: 
Create Date: 2026-03-02 16:46:01.217506+00:00

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '22b96fe61bcc'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('openai_api_key_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('anthropic_api_key_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('google_api_key_encrypted', sa.LargeBinary(), nullable=True))
    op.add_column('users', sa.Column('llm_config', postgresql.JSONB(astext_type=sa.Text()), server_default='{}', nullable=True, comment='User LLM provider configuration and settings'))
    op.drop_column('users', 'openai_api_key')
    op.drop_column('users', 'google_api_key')
    op.drop_column('users', 'anthropic_api_key')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('anthropic_api_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('google_api_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('openai_api_key', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('users', 'llm_config')
    op.drop_column('users', 'google_api_key_encrypted')
    op.drop_column('users', 'anthropic_api_key_encrypted')
    op.drop_column('users', 'openai_api_key_encrypted')
    # ### end Alembic commands ###
